### ISSUE TITLE
Add a sample of In-Graph

### ISSUE THREAD

**Issue by tangzhankun** [Intel-bigdata/TensorFlowOnYARN#12]
We need to know how in-graph application runs. If our current interfaces fit

**Comment by tangzhankun** [comment]
in-graph and between-graph roughly relation from our sample code:
Common: both needs to build ClusterSpec
Differences:
1. in-graph needs to have a list of train operation object while between graph only have one
2. in-graph needs a worker host as master while between graph doesn't need this

**Comment by manuzhang** [comment]
between-graph also needs a master which is passed in as`FLAG.target` and actually a worker host. I will update the between-graph example to align with in-graph

**Comment by tangzhankun** [comment]
yeah. thanks for the clarification. Does that means there are multiple master when running between-graph while only one for in-graph?

**Comment by manuzhang** [comment]
clients are free to submit graph to one or multiple masters in both between-graph and in-graph replication.  Master is for communication and distributing computation and should not be bound to the application type.

**Comment by tangzhankun** [comment]
I see. and do you think that we should make our current running job process optional? or just remove it?

**Comment by manuzhang** [comment]
I'd rather remove it. The current `job.py` is **not correct** since it launches two client scripts sequentially for between-graph replication. Users will want to run them concurrently. Another thing is if we interrupt the client we also kill the cluster while users may want to submit another application.

**Comment by manuzhang** [comment]
fixed in https://github.com/Intel-bigdata/TensorFlowOnYARN/commit/6f651060fcf21b0474efcbe6abf434020ad1ddf7. Discussions on launching TensorFlow client can continue at #17. Closing this.
