### ISSUE TITLE
Image for README

### ISSUE THREAD

**Issue by tangzhankun** [Intel-bigdata/TensorFlowOnYARN#13]
![toy_arch1](https://cloud.githubusercontent.com/assets/1171680/24279553/7fe214b0-1085-11e7-902e-a331ad61ba23.PNG)

**Comment by manuzhang** [comment]
Is there an arrow from HDFS to Node Manager ? Otherwise, why do we need step 1 ?

**Comment by tangzhankun** [comment]
yes. there should be. But I don't draw it because "distributed cache" is a mechanism supported by YARN. Anyone who knows YARN application development should know this. We're focusing on TOY control plane here. :)

**Comment by manuzhang** [comment]
where is "distributed cache" ? It's not in the image. I'm confused here.

**Comment by tangzhankun** [comment]
The "DS" is in the nodes' local directory. When a container request has a resource indicated by URI(mainly of HDFS), NM will download that resource to "DS" and make a soft-link to container's directory.

In this figure, I don't draw any YARN behaviors to avoid more messy lines.

**Comment by manuzhang** [comment]
The image has been attached to the README. Closing.
