### ISSUE TITLE
there are bugs when I compile use mvn clean package -DskipTests in the tensorflow-yarn-app

### ISSUE THREAD

**Issue by YuanshengHu** [Intel-bigdata/TensorFlowOnYARN#18]
logs:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 52.169 s
[INFO] Finished at: 2017-03-27T11:12:55+08:00
[INFO] Final Memory: 13M/201M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project tensorflow-yarn-app: Could not resolve dependencies for project com.github.hdl:tensorflow-yarn-app:jar:0.1.0-SNAPSHOT: Could not find artifact com.github.hdl:tensorflow-bridge:jar:0.1.0-SNAPSHOT in nexus-public-snapshots (http://maven.aliyun.com/nexus/content/repositories/snapshots/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by tangzhankun** [comment]
@manuzhang where is this bridge jar file (com.github.hdl:tensorflow-bridge:jar:0.1.0-SNAPSHOT)? Do we need to build it first? or the user can download it from public mvn repo?

**Comment by manuzhang** [comment]
has your codebase been updated to latest master ? The `tensorflow-bridge` project is built before `tensorflow-yarn-app`

**Comment by YuanshengHu** [comment]
yes, I have already build the libbridge.so, and put it into the bin directary

**Comment by manuzhang** [comment]
For build, please use `build.sh` after installing the [prerequisites of TensorFlow](https://www.tensorflow.org/install/install_sources)

**Comment by YuanshengHu** [comment]
okay,I think that the readme have to be update

**Comment by manuzhang** [comment]
The README has been updated. Closing.
