### ISSUE TITLE
Add design document

### ISSUE THREAD

**Issue by manuzhang** [Intel-bigdata/TensorFlowOnYARN#4]

**Comment by tangzhankun** [comment]
design document here:
https://docs.google.com/document/d/1EtAKg6-GwOa5-39GjccREm6y6DErEUUhNn4LfGzixjA/edit?usp=sharing

**Comment by manuzhang** [comment]
Added a new page in wiki https://github.com/Intel-bigdata/TensorFlowOnYARN/wiki/Design-Document
