### ISSUE TITLE
[QA] how to deal with this dependence issue

### ISSUE THREAD

**Issue by asagjj** [Intel-bigdata/TensorFlowOnYARN#48]
I git clone codes and compile with maven, maven cannot  resolve symbol "org.tensorflow.framework.ConfigProto" and "org.tensorflow.distruntime.ServerDef". It seems that pom.xml doesnot contain tensorflow dependences. what should I do before build?

**Comment by manuzhang** [comment]
TensorFlow dependencies are included as sub-modules. Did you try the following steps ?

```bash
git clone --recursive https://github.com/Intel-bigdata/TensorFlowOnYARN
cd TensorFlowOnYARN/tensorflow-parent
mvn package -Pnative -Pdist
```

**Comment by asagjj** [comment]
yeah ,this error  occurs when executing "mvn package -Pnative -Pdist". I resolved this problem on a machine with tensorflow env. but get...
"[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:single (dist) on project tensorflow-yarn-dist: Failed to create assembly: Error adding file to archive: /root/TensorFlowOnYARN/tensorflow-parent/tensorflow-yarn-dist/../tensorflow-native/tensorflow/bazel-bin/tensorflow/core/distributed_runtime/rpc/libbridge.so isn't a file"
 I couldnot get through for long.

**Comment by manuzhang** [comment]
It seems that TensorFlow native code fails to compile. You may firstly try running https://github.com/Intel-bigdata/TensorFlowOnYARN/blob/master/tensorflow-parent/tensorflow-native/tools/build.sh to see whether it succeeds.

**Comment by asagjj** [comment]
Done, thx
