### ISSUE TITLE
The client upload runtime so file(100MB) takes long time(5mins) to finish

### ISSUE THREAD

**Issue by tangzhankun** [Intel-bigdata/TensorFlowOnYARN#5]
Need to figure out if this is caused by HDFS or our implementation.

**Comment by wangyum** [comment]
Can you provide you Hadoop and Spark version?

**Comment by manuzhang** [comment]
I found a lot of warning as follow in datanode log 

```
org.apache.hadoop.hdfs.server.datanode.DataNode: Slow BlockReceiver write packet to mirror took 1667ms (threshold=300ms)
```

**Comment by manuzhang** [comment]
By the way, it also takes a while(~10s) to upload the jar file (2MB)

**Comment by manuzhang** [comment]
This is a network issue of our internal server. Closing.
